on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs: 
  pull:
    name: Pull
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.7
      - run: rm -rf ext-remover
      - run: git clone https://github.com/3kh0/ext-remover
      - run: rm -rf ext-remover/.git
      - run: ls
      - run: git config --global user.email "workflows@github.com" && git config --global user.name "the hub"
      - run: git add --all
      - run: git commit -m update
      - run: git push
